### ISSUE TITLE
Template parsing raises an error if I'm dynamically injecting template f.e. via webpack

### ISSUE THREAD

**Issue by jtomaszewski** [mgechev/codelyzer#106]
```ts
import { Inject, Component } from '@angular/core';

@Component({
  selector: 'rt-dashboard',
  template: require('./dashboard.html') as string
})
export class DashboardComponent {
}
```

This currently raises an error while trying to tslint the file:
```
/Users/jtomaszewski/src/sampleapp/rails/admin_app/node_modules/@angular/compiler/bundles/compiler.umd.js:4863
          this._length = _file.content.length;
                                      ^

TypeError: Cannot read property 'length' of undefined
    at new _Tokenizer (/Users/jtomaszewski/src/sampleapp/rails/admin_app/node_modules/@angular/compiler/bundles/compiler.umd.js:4863:39)
    at tokenize (/Users/jtomaszewski/src/sampleapp/rails/admin_app/node_modules/@angular/compiler/bundles/compiler.umd.js:4821:14)
    at HtmlParser.Parser.parse (/Users/jtomaszewski/src/sampleapp/rails/admin_app/node_modules/@angular/compiler/bundles/compiler.umd.js:5453:33)
    at HtmlParser.parse (/Users/jtomaszewski/src/sampleapp/rails/admin_app/node_modules/@angular/compiler/bundles/compiler.umd.js:7700:41)
    at I18NHtmlParser.parse (/Users/jtomaszewski/src/sampleapp/rails/admin_app/node_modules/@angular/compiler/bundles/compiler.umd.js:7326:46)
    at TemplateParser.tryParse (/Users/jtomaszewski/src/sampleapp/rails/admin_app/node_modules/@angular/compiler/bundles/compiler.umd.js:8511:52)
    at Object.exports.parseTemplate (/Users/jtomaszewski/src/sampleapp/rails/admin_app/node_modules/codelyzer/angular/templateParser.js:14:23)
    at OutputMetadataWalker.Ng2Walker.visitClassDecorator (/Users/jtomaszewski/src/sampleapp/rails/admin_app/node_modules/codelyzer/angular/ng2Walker.js:115:62)
    at Array.forEach (native)
    at OutputMetadataWalker.Ng2Walker.visitClassDeclaration (/Users/jtomaszewski/src/sampleapp/rails/admin_app/node_modules/codelyzer/angular/ng2Walker.js:72:40)
```

This is a 'brutal' error: it stops the tslint process, and f.e. in Atom editor, it shows a big red alert. Which forces me to turn off the tslint for the whole project ;/

I can see that https://github.com/mgechev/codelyzer/issues/94 is in progress. Instead of waiting for it, maybe could we have some workaround for it? For example, turn off parsing ng2 templates completely by some option in tslint.json ?

**Comment by mgechev** [comment]
Yes, the template rules don't work with external templates and support for webpack is not on the roadmap for near future. I'll take a look at the issue and make sure that this syntax doesn't throw an error.

**Comment by mgechev** [comment]
Fixed. Will be in master later today.

**Comment by jtomaszewski** [comment]
Works like a charm. Thanks! ;)
