### ISSUE TITLE
Migrate to Angular 2.1.0

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#115]

**Comment by karlhaas** [comment]
Problem with current versiona nd Angular 2.1.0:

```
/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8751
          template.animations.forEach(function (entry) { triggerLookup.add(entry.name); });
                  ^
TypeError: Cannot read property 'animations' of undefined
    at TemplateParseVisitor._validateElementAnimationInputOutputs (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8751:19)
    at TemplateParseVisitor.visitElement (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8734:20)
    at Element.visit (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:4656:78)
    at visit (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:4672:39)
    at /home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:4674:27
    at Array.forEach (native)
    at visitAll (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:4673:13)
    at TemplateParser.tryParseHtml (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8461:24)
    at TemplateParser.tryParse (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8451:23)
    at Object.exports.parseTemplate (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/codelyzer/angular/templateParser.js:14:23)
```

Will this be fixed by this issue or should i create a new issue?

**Comment by mgechev** [comment]
If you are using beta.1 this issue should be fine. The changes in 2.1.0 are not critical for codelyzer. Only an problem with the interpolation spans that I had to workaround was fixed.

**Comment by karlhaas** [comment]
@mgechev: thx! were using beta.0
