### ISSUE TITLE
__compiler_private__ removed from Angular 2.1.1

### ISSUE THREAD

**Issue by jSherz** [mgechev/codelyzer#128]
The `__compiler_private__` export was removed in Angular 2.1.1 and is used by `codelyzer/src/angular/templates/templateParser.ts`, leading to the following error when codelyzer is used with the latest Angular.

```
Cannot parse the template TypeError: Cannot read property 'TemplateParser' of undefined
    at Object.exports.parseTemplate (/home/user/project/node_modules/codelyzer/angular/templateParser.js:7:27)
    at Ng2Walker.visitClassDecorator (/home/user/project/node_modules/codelyzer/angular/ng2Walker.js:124:70)
    at Array.forEach (native)
    at Ng2Walker.visitClassDeclaration (/home/user/project/node_modules/codelyzer/angular/ng2Walker.js:73:40)
    at Ng2Walker.SyntaxWalker.visitNode (/home/user/project/node_modules/tslint/lib/language/walker/syntaxWalker.js:264:22)
    at /home/user/project/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/home/user/project/node_modules/typescript/lib/typescript.js:8251:30)
    at Object.forEachChild (/home/user/project/node_modules/typescript/lib/typescript.js:8411:24)
    at Ng2Walker.SyntaxWalker.walkChildren (/home/user/project/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:12)
    at Ng2Walker.SyntaxWalker.visitSourceFile (/home/user/project/node_modules/tslint/lib/language/walker/syntaxWalker.js:190:14)
    at Ng2Walker.SyntaxWalker.visitNode (/home/user/project/node_modules/tslint/lib/language/walker/syntaxWalker.js:414:22)
    at Ng2Walker.SyntaxWalker.walk (/home/user/project/node_modules/tslint/lib/language/walker/syntaxWalker.js:7:14)
    at Rule.AbstractRule.applyWithWalker (/home/user/project/node_modules/tslint/lib/language/rule/abstractRule.js:19:16)
    at Rule.apply (/home/user/project/node_modules/codelyzer/templatesUsePublicRule.js:87:21)
    at Linter.lint (/home/user/project/node_modules/tslint/lib/tslint.js:29:37)
    at Object.lint (/home/user/project/node_modules/tslint-loader/index.js:41:23)
```

If you've got any hints as to how I could fix this in a PR I'd love to contribute :)

**Comment by preslavsh** [comment]
This is fixed with the last merged and soon will be published in npm.

**Comment by jSherz** [comment]
That was super quick, thank you for your hard work! :+1:
