### ISSUE TITLE
Linting throws TypeError: value.slice is not a function

### ISSUE THREAD

**Issue by gingters** [mgechev/codelyzer#130]
Hi,

I get the following error while linting:

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: value.slice is not a function
    at new Rule (D:\Dev\project\node_modules\codelyzer\directiveSelectorPrefixRule.js:14:39)
    at Object.loadRules (D:\Dev\project\node_modules\tslint\lib\ruleLoader.js:23:28)
    at Linter.lint (D:\Dev\project\node_modules\tslint\lib\tslint.js:59:44)
    at D:\Dev\project\node_modules\gulp-tslint\index.js:104:30
    at wrappedMapper (D:\Dev\project\node_modules\map-stream\index.js:84:19)
    at Stream.stream.write (D:\Dev\project\node_modules\map-stream\index.js:96:21)
    at write (D:\Dev\project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (D:\Dev\project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (D:\Dev\project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
```

I'm using the following packages to lint my project:

```
    "typescript": "2.0.6",
    "gulp-typescript": "3.1.2",
    "codelyzer": "0.0.28", // also tried with 1.0.0-beta.3, same issue
    "tslint": "3.15.1",
    "gulp-tslint": "6.1.2"
```

And this is running on node 6.9.1 (also tried with 4.6.1).

**Comment by gingters** [comment]
Argh. Sorry, just noticed that I forgot to update the rules when updating...
