### ISSUE TITLE
Cannot read property 'TemplateParser' of undefined

### ISSUE THREAD

**Issue by KiT106** [mgechev/codelyzer#131]
I create new sample project using angular-cli v1.0.0-beta.19 and follow Tour of Heroes tutorial.
When I run `$ ng lint`, everything work fine.
However, when I run `$ tslint src/**/*.ts` or run it inside WebStorm, I get bellow error:
```
Cannot parse the template TypeError: Cannot read property 'TemplateParser' of undefined                                                                                                       
    at Object.exports.parseTemplate (D:\Samples\Project\Curly\node_modules\codelyzer\angular\templateParser.js:7:27)                                                                          
    at Ng2Walker.visitClassDecorator (D:\Samples\Project\Curly\node_modules\codelyzer\angular\ng2Walker.js:123:70)                                                                            
    at Array.forEach (native)                                                                                                                                                                 
    at Ng2Walker.visitClassDeclaration (D:\Samples\Project\Curly\node_modules\codelyzer\angular\ng2Walker.js:73:40)                                                                           
    at Ng2Walker.SyntaxWalker.visitNode (D:\Samples\Project\Curly\node_modules\tslint\lib\language\walker\syntaxWalker.js:264:22)                                                             
    at D:\Samples\Project\Curly\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63                                                                                                
    at visitEachNode (D:\Samples\Project\Curly\node_modules\typescript\lib\typescript.js:8338:30)                                                                                             
    at Object.forEachChild (D:\Samples\Project\Curly\node_modules\typescript\lib\typescript.js:8498:24)                                                                                       
    at Ng2Walker.SyntaxWalker.walkChildren (D:\Samples\Project\Curly\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)                                                          
    at Ng2Walker.SyntaxWalker.visitSourceFile (D:\Samples\Project\Curly\node_modules\tslint\lib\language\walker\syntaxWalker.js:190:14)    
```

**Comment by mgechev** [comment]
This issue is already fixed in the newest version of codelyzer (and the CLI, I suppose https://github.com/angular/angular-cli/pull/2615).

**Comment by mgechev** [comment]
@KiT106 as a fix you can install the latest version of codelyzer:

```
npm i codelyzer@1.0.0-beta.3 
```

**Comment by KiT106** [comment]
@mgechev Thanks you.
I'm using angular-cli to generate project. 
Seem angular-cli isn't using latest codelyzer version yet.
