### ISSUE TITLE
ComponentSelectorNameRule crashes if @Component() has no arg

### ISSUE THREAD

**Issue by ajafff** [mgechev/codelyzer#136]
Using `"component-selector-name": true` results in a crash of tslint

Example code:
```typescript
@Component()
class FooComponent{}
```
Console Output:
```
[...]\codelyzer\selectorNameBase.js:76
        if (arg.kind === SyntaxKind.current().ObjectLiteralExpression) {
               ^

TypeError: Cannot read property 'kind' of undefined
    at SelectorNameValidatorWalker.validateSelector ([...]\codelyzer\selectorNameBase.js:76:16)
    at SelectorNameValidatorWalker.validateDecorator ([...]\codelyzer\selectorNameBase.js:71:18)
    at Array.forEach (native)
    at SelectorNameValidatorWalker.visitClassDeclaration ([...]\codelyzer\selectorNameBase.js:59:14)
    at SelectorNameValidatorWalker.SyntaxWalker.visitNode ([...]\tslint\lib\language\walker\syntaxWalker.js:264:22)
    at c:\WKS\IntelliJIdea\optica-frontend\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
    at visitEachNode ([...]\typescript\lib\typescript.js:8338:30)
    at Object.forEachChild ([...]\typescript\lib\typescript.js:8498:24)
    at SelectorNameValidatorWalker.SyntaxWalker.walkChildren ([...]\tslint\lib\language\walker\syntaxWalker.js:459:12)
    at SelectorNameValidatorWalker.SyntaxWalker.visitSourceFile ([...]\tslint\lib\language\walker\syntaxWalker.js:190:14)
```

Expected bahaviour:
Maybe print error that one argument is required, but do not crash.

This problem is really nasty if your IDE automatically runs tslint, which then crashes.

**Comment by artaommahe** [comment]
@mgechev it crashes at this cases
```
export function createComponentMock(componentOptions: Component) {
  if (!componentOptions.template) {
    componentOptions = { ...componentOptions, template: '' };
  }

  @Component(componentOptions)
  class SomeComponent {}

  return SomeComponent;
}
```
last version

**Comment by mgechev** [comment]
@artaommahe are all the peer dependencies satisfied? If not, it's probably an incompatible TypeScript version.

**Comment by artaommahe** [comment]
@mgechev 
```
└─ codelyzer@4.5.0
└─ tslint@5.12.1
└─ @angular/compiler@7.0.3
└─ @angular/core@7.0.3
```
