### ISSUE TITLE
Unsupported TypeScript version: 2.2.0-dev

### ISSUE THREAD

**Issue by sasxa** [mgechev/codelyzer#149]
I'm getting an error when I use `typescript@next` (angular-cli project, vscode editor). 
It works with `typescript@latest` 2.0.9, and `typescript@rc` 2.1.1, but not with `typescript@next` 2.2.0-dev. My guess is that this is related to the new features - Object spread and rest.

Any chance to add support for this?

```
[Info  - 17.59.10] vscode-tslint: 'Unsupported TypeScript version: 2.2.0-dev.20161114' while validating: ~\src\app\app.module.ts stacktrace: Error: Unsupported TypeScript version: 2.2.0-dev.20161114
    at Object.current (~\node_modules\codelyzer\util\syntaxKind.js:2120:23)
    at ClassMetadataWalker.visitClassDeclaration (~\node_modules\codelyzer\useLifeCycleInterfaceRule.js:45:37)
    at ClassMetadataWalker.SyntaxWalker.visitNode (~\node_modules\tslint\lib\language\walker\syntaxWalker.js:264:22)
    at ~\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
    at visitEachNode (~\node_modules\typescript\lib\typescript.js:13851:30)
    at Object.forEachChild (~\node_modules\typescript\lib\typescript.js:14022:24)
    at ClassMetadataWalker.SyntaxWalker.walkChildren (~\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)
    at ClassMetadataWalker.SyntaxWalker.visitSourceFile (~\node_modules\tslint\lib\language\walker\syntaxWalker.js:190:14)
    at ClassMetadataWalker.SyntaxWalker.visitNode (~\node_modules\tslint\lib\language\walker\syntaxWalker.js:414:22)
    at ClassMetadataWalker.SyntaxWalker.walk (~\node_modules\tslint\lib\language\walker\syntaxWalker.js:7:14)
```

**Comment by mgechev** [comment]
Yes there's not support for TypeScript 2.2.0 at this point. We'll add it in the next a couple of days.

**Comment by e-cloud** [comment]
what should be updated for supporting TS 2.2.0. I may give a hand on this :smile:
