### ISSUE TITLE
 Could not find implementations for the following rules... Error

### ISSUE THREAD

**Issue by gruppjo** [mgechev/codelyzer#154]
Hi everybody,

### Description
I just tried to setup codelyzer for my project and I ran into the following problem:

> The `component-selector` and `directive-selector` produce the following error:

```sh
throw new Error(ERROR_MESSAGE);
        ^

Error: 
            Could not find implementations for the following rules specified in the configuration:
            directive-selector
component-selector
            Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
            If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
        
    at Object.loadRules (/Users/jonathan/Projects/play/codelyzer-issue/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/Users/jonathan/Projects/play/codelyzer-issue/node_modules/tslint/lib/tslint.js:59:44)
    at processFile (/Users/jonathan/Projects/play/codelyzer-issue/node_modules/tslint/lib/tslint-cli.js:138:29)
    at /Users/jonathan/Projects/play/codelyzer-issue/node_modules/tslint/lib/tslint-cli.js:177:74
    at Array.forEach (native)
    at Object.<anonymous> (/Users/jonathan/Projects/play/codelyzer-issue/node_modules/tslint/lib/tslint-cli.js:177:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```
### Reproduce
I prepared a minimal setup to reproduce the issue https://github.com/gruppjo/codelyzer-issue

**Comment by mgechev** [comment]
Thanks for the detailed explanation of the issue you have! Yes, currently `directive-selector` and `component-selector` are in master but not yet published. You can use the [configuration explained on npm](https://www.npmjs.com/package/codelyzer). Good luck! Let me know if you have any other problems.

**Comment by gruppjo** [comment]
Oh. Wasn't aware of that. Sorry! And thanks for the swift response! :)
