### ISSUE TITLE
importDestructuringSpacingRule.js causing "Error: Cannot find module 'tslint/lib/lint'"

### ISSUE THREAD

**Issue by ammarhaider7** [mgechev/codelyzer#159]
Running npm run lint from the latest [angular2-webpack-starter repo](https://github.com/AngularClass/angular2-webpack-starter) causes the following error that seems to be originating from importDestructuringSpacingRule.js which wasn't happening a few days ago.

```$ npm run lint

> angular2-webpack-starter@5.1.1 lint C:\Users\ammar.haider\oakbrook\angular2-webpack-starter
> npm run tslint "src/**/*.ts"


> angular2-webpack-starter@5.1.1 tslint C:\Users\ammar.haider\oakbrook\angular2-webpack-starter
> tslint "src/**/*.ts"

no-unused-variable is deprecated. Use the tsc compiler options --noUnusedParameters and --noUnusedLocals instead.
module.js:471
    throw err;
    ^

Error: Cannot find module 'tslint/lib/lint'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ammar.haider\oakbrook\angular2-webpack-starter\node_modules\codelyzer\importDestructuringSpacingRule.js:8:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by mgechev** [comment]
They have updated to tslint 4, which support is not released yet by codelyzer. By the end of the week it should be in npm. You can open an issue in angular2-webpack-starter, most likely they have mismatched peerDependencies.

**Comment by ammarhaider7** [comment]
@mgechev thanks Minko!
