### ISSUE TITLE
Error with TSLint 4.0.1

### ISSUE THREAD

**Issue by michaeljota** [mgechev/codelyzer#162]
When trying to run with lastes TSLint v4.0.1, throws:

```cmd
module.js:457
    throw err;
    ^

Error: Cannot find module 'tslint/lib/lint'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\proyectos\pronetworks\sistapro-web@ultimate-material2\node_modules\codelyzer\selectorNameBase.js:8:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by mgechev** [comment]
Duplication of https://github.com/mgechev/codelyzer/issues/161 and https://github.com/mgechev/codelyzer/issues/157.

**Comment by gligoran** [comment]
Hey! Any plans on releasing this soon?

**Comment by mgechev** [comment]
Once we have external template support. Probably by the beginning of the next week.

**Comment by mgechev** [comment]
You can now use `2.0.0-beta.1` which works with tslint 4.
