### ISSUE TITLE
error in atom-typescript

### ISSUE THREAD

**Issue by spali** [mgechev/codelyzer#183]
I have an error with some specific rules of codelyzer in atom-typescript.
The strange thing is, it works on cli with tslint.
Probably it's a tslint issue, but I only can reproduce it with codelyzer and only since switching to tslint 4 and codelyzer 2.
I detected it in a project based on angular-seed. And it started with the following commit mgechev/angular-seed@d3eb166.

I could make it down to the rules listed in the `tslint.json` of the project (except the `max-line-length` it's just for clarification, the tslint works).
I bet it is somehow related to #181 because the same affected rules.

It seems that in atom-typescript, the path to app-root-path could not be resolved.

here is a project to reproduce: https://github.com/spali/codelyzer-error
1. clone repo
2. `npm install`
3. open src/test.ts in atom with atom-typescript.

Throws the following error in atom:
```
Error: Cannot find module 'app-root-path'
Error: Cannot find module 'app-root-path'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Data\STH\_Apps\Atom\Atom\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at EventEmitter.<anonymous> (C:\Data\STH\_Apps\Atom\Atom\resources\electron.asar\browser\rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (C:\Data\STH\_Apps\Atom\Atom\resources\electron.asar\browser\api\web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:\Data\STH\_Apps\Atom\Atom\resources\electron.asar\renderer\api\remote.js:210:13)
    at Object.exports.require (C:\Data\STH\_Apps\Atom\Atom\resources\electron.asar\renderer\api\remote.js:297:10)
    at Object.electron.remote.require (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\electron-shims.js:78:28)
    at resolve (C:\Data\_git\irt-web\xxx\node_modules\app-root-path\lib\resolve.js:32:17)
    at module.exports (C:\Data\_git\irt-web\xxx\node_modules\app-root-path\lib\app-root-path.js:6:20)
    at Object.<anonymous> (C:\Data\_git\irt-web\xxx\node_modules\app-root-path\index.js:4:18)
    at Module._compile (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Data\_git\irt-web\xxx\node_modules\codelyzer\angular\config.js:25:12)
    at Module._compile (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Data\_git\irt-web\xxx\node_modules\codelyzer\angular\templates\templateParser.js:4:16)
    at Module._compile (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Data\_git\irt-web\xxx\node_modules\codelyzer\angular\ng2Walker.js:10:24)
    at Module._compile (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Data\_git\irt-web\xxx\node_modules\codelyzer\noInputRenameRule.js:9:19)
    at Module._compile (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Data\STH\_Apps\Atom\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at loadRule (C:\Data\_git\irt-web\xxx\node_modules\tslint\lib\ruleLoader.js:107:26)
    at findRule (C:\Data\_git\irt-web\xxx\node_modules\tslint\lib\ruleLoader.js:82:20)
    at Object.loadRules (C:\Data\_git\irt-web\xxx\node_modules\tslint\lib\ruleLoader.js:33:24)
    at Linter.getEnabledRules (C:\Data\_git\irt-web\xxx\node_modules\tslint\lib\linter.js:163:44)
    at Linter.lint (C:\Data\_git\irt-web\xxx\node_modules\tslint\lib\linter.js:78:33)
    at file:///C:/Users/sth/.atom/packages/linter-tslint/lib/main.js:149:18
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Removing the rules except `max-line-length` and there is no error thrown.

__Environment__
```
Platform: Windows 7
Atom: 1.12.6
atom-typescript: 10.1.12
```

**Comment by mgechev** [comment]
This is a known issue and it's fixed in master. Should be out in a couple of days/week. https://github.com/mgechev/codelyzer/pull/177

**Comment by spali** [comment]
thanks! :+1: 
searched at least a couple of times for this specific error here and didn't got this Issue in the search results :(

**Comment by mgechev** [comment]
No worries, hopefully I will be able to release it soon.
