### ISSUE TITLE
Error related to rules 'no-access-missing-member' and 'templates-use-public'

### ISSUE THREAD

**Issue by Yura13** [mgechev/codelyzer#276]
### Bug Report
I have the error when running `ng lint --type-check` (`tslint --type-check --project src/tsconfig.app.json`). If you run `ng lint` in a console you will see next warnings: 
```
Warning: The 'use-life-cycle-interface' rule requires type checking
Warning: The 'no-access-missing-member' rule requires type checking
Warning: The 'templates-use-public' rule requires type checking
```
### Error
```
Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
    at simplify (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23308:54)
    at simplifyCall (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23114:24)
    at simplify (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23296:48)
    at simplifyInContext (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23321:24)
    at simplify (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23157:36)
    at simplifyInContext (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23321:24)
    at simplify (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23279:48)
    at simplify (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23139:56)
    at simplifyInContext (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23321:24)
    at recordedSimplifyInContext (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23334:24) 'node_modules/@angular/core/core.d.ts'
```
#### Version of packages:
```
    "@angular/animations": "4.0.1",
    "@angular/common": "4.0.1",
    "@angular/compiler": "4.0.1",
    "@angular/core": "4.0.1",
    "@angular/forms": "4.0.1",
    "@angular/http": "4.0.1",
    "@angular/platform-browser": "4.0.1",
    "@angular/platform-browser-dynamic": "4.0.1",
    "@angular/router": "4.0.1",
    "core-js": "2.4.1",
    "primeng": "4.0.0-rc.2",
    "rxjs": "5.2.0",
    "zone.js": "0.8.5"
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "4.0.1",
    "@types/node": "7.0.12",
    "codelyzer": "3.0.0-beta.4",
    "ts-node": "3.0.2",
    "tslint": "4.5.1",
    "typescript": "2.2.2"
```

`tslint.json` configuration - default generated by angular-cli 1.0.0
When I remove  "no-access-missing-member": true and "templates-use-public": true from `tslint.json` tslint running without any errors.

**Comment by mgechev** [comment]
Codelyzer 3 is still in beta. Once it gets stable these errors will be gone and we will publish the final release.

**Comment by leocaseiro** [comment]
I'm using `codelyzer@3.0.0`, and the warning was still happening:

```Warning: The 'no-use-before-declare' rule requires type checking```

To fix, just run `ng lint` with `typeCheck`, and the warning is gone:

```ng lint --typeCheck```
