### ISSUE TITLE
Issue parsing ts file

### ISSUE THREAD

**Issue by denodaeus** [mgechev/codelyzer#28]
```
/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/codelyzer/noAttributeParameterDecoratorRule.js:30
        var parentName = node.parent.name.text;
                                         ^

TypeError: Cannot read property 'text' of undefined
    at ConstructorMetadataWalker.visitConstructorDeclaration (/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/codelyzer/noAttributeParameterDecoratorRule.js:30:42)
    at ConstructorMetadataWalker.SyntaxWalker.visitNode (/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/tslint/lib/language/walker/syntaxWalker.js:264:22)
    at /Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/tslint/lib/language/walker/syntaxWalker.js:441:63
    at visitEachNode (/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/typescript/lib/typescript.js:7255:30)
    at Object.forEachChild (/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/typescript/lib/typescript.js:7484:21)
    at ConstructorMetadataWalker.SyntaxWalker.walkChildren (/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/tslint/lib/language/walker/syntaxWalker.js:441:12)
    at ConstructorMetadataWalker.SyntaxWalker.visitNode (/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/tslint/lib/language/walker/syntaxWalker.js:435:22)
    at /Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/tslint/lib/language/walker/syntaxWalker.js:441:63
    at visitNode (/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/typescript/lib/typescript.js:7243:20)
    at Object.forEachChild (/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/typescript/lib/typescript.js:7303:21)
```

A gist of the file:  [here](https://gist.github.com/denodaeus/99617ff838cb6215b4757411a86165cb)
tslint.json:  [here](https://gist.github.com/denodaeus/f3b8201498cbcbe32b71e37b715acad0)

```
tsc -v
Version 1.8.10
```

```
tslint -v
3.9.0
```

**Comment by mgechev** [comment]
Thanks for reporting this out! I can take a look right after ng-conf.

@preslavsh can you take a look at the issue by then?

**Comment by preslavsh** [comment]
The problems occurs, when class is declared as property.
`  static SampleTestCase = class extends TestCase {
    constructor() {
    }`

It is fixed here: #29

**Comment by preslavsh** [comment]
Thanks for sharing the problem. The issue is fixed.

**Comment by denodaeus** [comment]
Awesome, thanks.
