### ISSUE TITLE
'templates-use-public' throws error when attempting to access a property of a property with the [] syntax

### ISSUE THREAD

**Issue by TomCaserta** [mgechev/codelyzer#315]
**Rule**: templates-use-public
**Codealyzer Version**: 3.0.1
**Angular Version**: 4.1.3

### Minimal Snippet

Interface:
```TypeScript

interface Something {
    a;
    b;
}

@Component({
    template: '<span>{{ something[0].a }}</span>'
})
export class DemoComponent {
    public something: Something[] = [{ a: 1, b: 2 }];
}
```

Class:
```TypeScript
class Something {
    public a = 1;
    public b = 2;
}

@Component({
    template: '<span>{{ something[0].a }}</span>'
})
export class DemoComponent {
    public something: Something[] = [new Something()];
}
```

No class/interface definition:
```TypeScript
@Component({
    template: '<span>{{ something["a"].b }}</span>'
})
export class DemoComponent {
    public something: { a: any } = { a: { b: 1 } };
}
```

### Error Displayed

```
Cannot parse the template of DemoComponent TypeError: Cannot read property 'name' of undefined
    at SymbolAccessValidator.doCheck (/path/to/project/node_modules/codelyzer/templatesUsePublicRule.js:36:37)
    at SymbolAccessValidator.visitPropertyRead (/path/to/project/node_modules/codelyzer/templatesUsePublicRule.js:24:21)
    at PropertyRead.visit (/path/to/project/node_modules/@angular/compiler/@angular/compiler.es5.js:2540:15)
    at SymbolAccessValidator.RecursiveAngularExpressionVisitor.visit (/path/to/project/node_modules/codelyzer/angular/templates/recursiveAngularExpressionVisitor.js:18:13)
    at /path/to/project/node_modules/codelyzer/angular/templates/recursiveAngularExpressionVisitor.js:46:64
    at Array.forEach (native)
    at SymbolAccessValidator.RecursiveAngularExpressionVisitor.visitInterpolation (/path/to/project/node_modules/codelyzer/angular/templates/recursiveAngularExpressionVisitor.js:46:25)
    at Interpolation.visit (/path/to/project/node_modules/@angular/compiler/@angular/compiler.es5.js:2758:23)
    at SymbolAccessValidator.RecursiveAngularExpressionVisitor.visit (/path/to/project/node_modules/codelyzer/angular/templates/recursiveAngularExpressionVisitor.js:18:13)
    at BasicTemplateAstVisitor.visitNgTemplateAST (/path/to/project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:67:25)
    at BasicTemplateAstVisitor.visitBoundText (/path/to/project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:111:18)
    at BoundTextAst.visit (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:87:24)
    at BasicTemplateAstVisitor.visit (/path/to/project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:71:14)
    at /path/to/project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:89:62
    at Array.forEach (native)
    at BasicTemplateAstVisitor.visitElement (/path/to/project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:89:26)
```

**Comment by mgechev** [comment]
Thanks for reporting the issue. Will fix it as soon as possible and release it.

**Comment by mgechev** [comment]
@TomCaserta cannot reproduce the issue https://github.com/mgechev/codelyzer/pull/318
