### ISSUE TITLE
Could not find the following rules specified in the configuration

### ISSUE THREAD

**Issue by yahyaKacem** [mgechev/codelyzer#34]
first thanks for this I have been struggling on how to enforce this rules, I just installed this and tried it it worked without the [Recommended configuration](https://github.com/mgechev/codelyzer#recommended-configuration), but once I add those it gives me this error (with tslint cli):
`global tslint v: 3.9.0`
>/home/yahya/.nvm/versions/node/v5.10.1/lib/node_modules/tslint/lib/ruleLoader.js:29
        throw new Error(errorMessage);
        ^
Error: Could not find the following rules specified in the configuration:
directive-selector-prefix
component-selector-prefix
use-input-property-decorator
use-output-property-decorator
use-host-property-decorator
no-attribute-parameter-decorator
no-input-rename
no-output-rename
no-forward-ref
use-life-cycle-interface
use-pipe-transform-interface
pipe-naming
component-class-suffix
directive-class-suffix
    at Object.loadRules (/home/yahya/.nvm/versions/node/v5.10.1/lib/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/home/yahya/.nvm/versions/node/v5.10.1/lib/node_modules/tslint/lib/tslint.js:25:44)
    at processFile (/home/yahya/.nvm/versions/node/v5.10.1/lib/node_modules/tslint/lib/tslint-cli.js:118:29)
    at Array.forEach (native)
    at Object.<anonymous> (/home/yahya/.nvm/versions/node/v5.10.1/lib/node_modules/tslint/lib/tslint-cli.js:128:41)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

with gulp tslint:
```
local tslint v: 3.9.0
gulp-tslint v:5.0.0
```
>/var/www/Work/card/node_modules/gulp-tslint/node_modules/tslint/lib/ruleLoader.js:29
        throw new Error(errorMessage);
              ^
Error: Could not find the following rules specified in the configuration:
no-trailing-comma
directive-selector-prefix
component-selector-prefix
use-input-property-decorator
use-output-property-decorator
use-host-property-decorator
no-attribute-parameter-decorator
no-input-rename
no-output-rename
no-forward-ref
use-life-cycle-interface
use-pipe-transform-interface
pipe-naming
component-class-suffix
directive-class-suffix
    at Object.loadRules (/var/www/Work/card/node_modules/gulp-tslint/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/var/www/Work/card/node_modules/gulp-tslint/node_modules/tslint/lib/tslint.js:25:44)
    at /var/www/Work/card/node_modules/gulp-tslint/index.js:95:34
    at respond (/var/www/Work/card/node_modules/gulp-tslint/node_modules/rcloader/index.js:68:7)
    at respond (/var/www/Work/card/node_modules/gulp-tslint/node_modules/rcloader/node_modules/rcfinder/index.js:140:7)
    at /var/www/Work/card/node_modules/gulp-tslint/node_modules/rcloader/node_modules/rcfinder/index.js:124:17
    at /var/www/Work/card/node_modules/gulp-tslint/node_modules/rcloader/node_modules/rcfinder/index.js:77:13
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by mgechev** [comment]
With gulp-tslint you need to specify the rulesDirectory property inline, in gulpfile.js. Take a look at angular.io's gulpfile for details.
