### ISSUE TITLE
Error while parsing TS file with mixin

### ISSUE THREAD

**Issue by adros** [mgechev/codelyzer#422]
I get this error, 

    TypeError: Cannot read property 'text' of undefined at /home/UX/arakovskyux/workspaces/pvzp-clfe/node_modules/codelyzer/noAttributeParameterDecoratorRule.js:52:42
        at /home/UX/arakovskyux/workspaces/pvzp-clfe/node_modules/codelyzer/util/function.js:26:59
        at Maybe.bind (/home/UX/arakovskyux/workspaces/pvzp-clfe/node_modules/codelyzer/util/function.js:21:20)
        at Maybe.fmap (/home/UX/arakovskyux/workspaces/pvzp-clfe/node_modules/codelyzer/util/function.js:26:21)
        at /home/UX/arakovskyux/workspaces/pvzp-clfe/node_modules/codelyzer/noAttributeParameterDecoratorRule.js:50:14
        at Object.validate (/home/UX/arakovskyux/workspaces/pvzp-clfe/node_modules/codelyzer/walkerFactory/walkerFn.js:18:82)
        at /home/UX/arakovskyux/workspaces/pvzp-clfe/node_modules/codelyzer/walkerFactory/walkerFn.js:53:27
        at Array.forEach (native)
        at class_1.visitNode (/home/UX/arakovskyux/workspaces/pvzp-clfe/node_modules/codelyzer/walkerFactory/walkerFn.js:51:28)
        at /home/UX/arakovskyux/workspaces/pvzp-clfe/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63`

when my code contains declaration of a mixin
(https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-22)

E.g. something like this

    type Constructor<T> = new (...args: any[]) => T;

    export function MyUtils<T extends Constructor<{}>>(Base: T) {
      return class extends Base {
        public myMethod(a, b): boolean {
          ....
        }
      };
    }

It may be related to issue #28.

I am using latest version 3.2.0

**Comment by mgechev** [comment]
@adros thanks for sharing the issue. I'll take a look at it today.

**Comment by mgechev** [comment]
The issue should be fixed soon https://github.com/mgechev/codelyzer/pull/423.
