### ISSUE TITLE
Angular lint(codelyzer) failing with TypeError

### ISSUE THREAD

**Issue by YiannisH** [mgechev/codelyzer#484]
When i try to run the code analysis command 

> **npm run lint -- --format checkstyle**

I get the following output repeatedly before the actual checkstyle XML code starts

```
TypeError: Cannot read property 'parse' of null
    at TemplateParser.tryParse (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\@angular\compiler\bundles\compiler.umd.js:24699:117)
    at Object.exports.parseTemplate (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\templates\templateParser.js:82:29)
    at InputMetadataWalker.Ng2Walker.visitNg2Component (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\ng2Walker.js:114:52)
    at InputMetadataWalker.Ng2Walker.visitClassDeclaration (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\ng2Walker.js:50:18)
    at InputMetadataWalker.SyntaxWalker.visitNode (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:311:22)
    at C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:529:63
    at visitEachNode (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\typescript\lib\typescript.js:16136:24)
    at InputMetadataWalker.SyntaxWalker.walkChildren (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:529:12)
    at InputMetadataWalker.SyntaxWalker.visitSourceFile (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:225:14)
TypeError: Cannot read property 'parse' of null
    at TemplateParser.tryParse (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\@angular\compiler\bundles\compiler.umd.js:24699:117)
    at Object.exports.parseTemplate (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\templates\templateParser.js:82:29)
    at OutputMetadataWalker.Ng2Walker.visitNg2Component (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\ng2Walker.js:114:52)
    at OutputMetadataWalker.Ng2Walker.visitClassDeclaration (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\ng2Walker.js:50:18)
    at OutputMetadataWalker.SyntaxWalker.visitNode (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:311:22)
    at C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:529:63
    at visitEachNode (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\typescript\lib\typescript.js:16136:24)
    at OutputMetadataWalker.SyntaxWalker.walkChildren (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:529:12)
    at OutputMetadataWalker.SyntaxWalker.visitSourceFile (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:225:14)
TypeError: Cannot read property 'parse' of null
    at TemplateParser.tryParse (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\@angular\compiler\bundles\compiler.umd.js:24699:117)
    at Object.exports.parseTemplate (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\templates\templateParser.js:82:29)
    at class_1.Ng2Walker.visitNg2Component (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\ng2Walker.js:114:52)
    at class_1.visitNg2Component (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\walkerFactory\walkerFn.js:46:52)
    at class_1.Ng2Walker.visitClassDeclaration (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\ng2Walker.js:50:18)
    at class_1.SyntaxWalker.visitNode (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:311:22)
    at class_1.visitNode (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\walkerFactory\walkerFn.js:55:44)
    at C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:529:63
    at visitEachNode (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\typescript\lib\typescript.js:16136:24)
TypeError: Cannot read property 'parse' of null
    at TemplateParser.tryParse (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\@angular\compiler\bundles\compiler.umd.js:24699:117)
    at Object.exports.parseTemplate (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\templates\templateParser.js:82:29)
    at ClassMetadataWalker.Ng2Walker.visitNg2Component (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\ng2Walker.js:114:52)
    at ClassMetadataWalker.Ng2Walker.visitClassDeclaration (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\codelyzer\angular\ng2Walker.js:50:18)
    at ClassMetadataWalker.SyntaxWalker.visitNode (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:311:22)
    at C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:529:63
    at visitEachNode (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\typescript\lib\typescript.js:16136:24)
    at ClassMetadataWalker.SyntaxWalker.walkChildren (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:529:12)
    at ClassMetadataWalker.SyntaxWalker.visitSourceFile (C:\ProjectsSources\angular\PROJ\PROJ-Portals\node_modules\tslint\lib\language\walker\syntaxWalker.js:225:14)

```
The issue can observed on both Windows and Linux OSes

NPM and Node versions:
npm v5.6.0
node v9.3.0

package.json code

```
{
  "name": "PORTALS",
  "version": "0.0.1",
  "license": "TEST",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build": "ng build"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/schematics": "0.0.34",
    "@angular/animations": "5.1.1",
    "@angular/common": "5.1.1",
    "@angular/compiler": "5.1.1",
    "@angular/core": "5.1.1",
    "@angular/forms": "5.1.1",
    "@angular/http": "5.1.1",
    "@angular/platform-browser": "5.1.1",
    "@angular/platform-browser-dynamic": "5.1.1",
    "@angular/router": "5.1.1",
    "angular2-jwt": "0.2.0",
    "bootstrap": "4.0.0-alpha.6",
    "chart.js": "2.6.0",
    "core-js": "2.4.1",
    "font-awesome": "4.7.0",
    "jquery": "3.2.1",
    "npm-font-open-sans": "1.0.3",
    "primeng": "5.0.2",
    "quill": "1.3.0",
    "rxjs": "5.5.2",
    "tether": "1.4.0",
    "zone.js": "0.8.5"
  },
  "devDependencies": {
    "@angular/cli": "1.4.0",
    "@angular/compiler-cli": "5.1.1",
    "@types/jasmine": "2.5.46",
    "@types/jquery": "2.0.41",
    "@types/node": "7.0.12",
    "angular-in-memory-web-api": "0.5.0",
    "codelyzer": "3.0.0-beta.4",
    "jasmine-core": "2.5.2",
    "jasmine-reporters": "2.2.1",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.5.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.0.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-junit-reporter": "1.2.0",
    "karma-phantomjs-launcher": "1.0.4",
    "protractor": "5.1.2",
    "ts-node": "^3.3.0",
    "tslint": "5.4.3",
    "typescript": "2.4.2"
  }
}

```

**Comment by mgechev** [comment]
@YiannisH thanks for reporting this. Maybe a breaking API change in Angular 5.1.x...

**Comment by YiannisH** [comment]
Is there a way to fix this? I have been searching all morning and i was unable to find exactly the same issue. There were some similar issues on github that had their issues fixed by using older versions of the involved packages but those solutions refer to different issues. 

Just writing this here as it might help the development team to identify the issue.

**Comment by mgechev** [comment]
For now you can disable the codelyzer rules. I will try to publish a fix over the weekend if I am able to reproduce the issue.

**Comment by YiannisH** [comment]
Any news on the issue above??

**Comment by rafaelss95** [comment]
Is it still an issue with the latest version?
