### ISSUE TITLE
noForwardRefRule crash

### ISSUE THREAD

**Issue by achimha** [mgechev/codelyzer#49]
Using Typescript 1.8.10, tslint 3.10.2 and codelyzer 0.0.19, I get a crash when evaluating the following code:

```
const CUSTOM_VALUE_ACCESSOR = new Provider(
    NG_VALUE_ACCESSOR, { useExisting: forwardRef(() => CountryListValueAccessor)});
```

This is what appears in the log, executed via Webstorm:

```
2016-06-03 09:28:23,062 [421353309]   INFO - avascript.linter.tslint.TsLint - TsLint inner error. TsLint version: 3.10.2

/usr/local/lib/node_modules/codelyzer/noForwardRefRule.js:36
var failureConfig = [currentNode.name.text];
^

TypeError: Cannot read property 'text' of undefined
at ExpressionCallMetadataWalker.validateCallExpression (/usr/local/lib/node_modules/codelyzer/noForwardRefRule.js:36:50)
at ExpressionCallMetadataWalker.visitCallExpression (/usr/local/lib/node_modules/codelyzer/noForwardRefRule.js:27:14)
at ExpressionCallMetadataWalker.SyntaxWalker.visitNode (/usr/local/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:249:22)
at /usr/local/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:447:63
at visitNode (/usr/local/lib/node_modules/typescript/lib/typescript.js:7243:20)
at Object.forEachChild (/usr/local/lib/node_modules/typescript/lib/typescript.js:7303:21)
at ExpressionCallMetadataWalker.SyntaxWalker.walkChildren (/usr/local/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:447:12)
at ExpressionCallMetadataWalker.SyntaxWalker.visitPropertyAssignment (/usr/local/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:166:14)
at ExpressionCallMetadataWalker.SyntaxWalker.visitNode (/usr/local/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:384:22)
at /usr/local/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:447:63
```

**Comment by mgechev** [comment]
Seems like a duplication of https://github.com/mgechev/codelyzer/issues/42, so the issue is already fixed. I'll release `0.0.20` today, let me know if you still experience it.

I also added an extra test case https://github.com/mgechev/codelyzer/commit/80dd6737e3041223384cb849c1deb4f50ae4886d.
