### ISSUE TITLE
Pipe-naming's config kebab-case has not bean implement

### ISSUE THREAD

**Issue by chengwanxin9825** [mgechev/codelyzer#565]
"codelyzer": "4.2.1",
tslint.json 
        "pipe-naming": {
            "options": ["kebab-case"],
            "severity": "error"
        },

I have confirmed the source (pipeNamingRule.js )
The problem is that  [_this.validator] has notbean Initialized when args[0]=kebab-case

        if (args[0] === 'camelCase') {
            _this.validator = selectorValidator_1.SelectorValidator.camelCase;
        }

I will get the error:
TypeError: this.validator is not a function
    at Rule.validateName (C:\Users\WQ35311\Desktop\04_WORKSPACE\00-WORKSPACE\billnet_client\node_modules\codelyzer\pipeNamingRule.js:41:21)
    at ClassMetadataWalker.validateProperty (C:\Users\WQ35311\Desktop\04_WORKSPACE\00-WORKSPACE\billnet_client\node_modules\codelyzer\pipeNamingRule.js:105:41)
    at Array.forEach (<anonymous>)
    at ClassMetadataWalker.validateProperties (C:\Users\WQ35311\Desktop\04_WORKSPACE\00-WORKSPACE\billnet_client\node_modules\codelyzer\pipeNamingRule.js:90:18)
    at ClassMetadataWalker.visitNgPipe (C:\Users\WQ35311\Desktop\04_WORKSPACE\00-WORKSPACE\billnet_client\node_modules\codelyzer\pipeNamingRule.js:83:14)
    at ClassMetadataWalker.NgWalker.visitClassDecorator (C:\Users\WQ35311\Desktop\04_WORKSPACE\00-WORKSPACE\billnet_client\node_modules\codelyzer\angular\ngWalker.js:104:18)
    at Array.forEach (<anonymous>)
    at ClassMetadataWalker.NgWalker.visitClassDeclaration (C:\Users\WQ35311\Desktop\04_WORKSPACE\00-WORKSPACE\billnet_client\node_modules\codelyzer\angular\ngWalker.js:55:40)
    at ClassMetadataWalker.SyntaxWalker.visitNode (C:\Users\WQ35311\Desktop\04_WORKSPACE\00-WORKSPACE\billnet_client\node_modules\tslint\lib\language\walker\syntaxWalker.js:314:22)
    at C:\Users\WQ35311\Desktop\04_WORKSPACE\00-WORKSPACE\billnet_client\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
ERROR: (file-header) C:/Users/WQ35311/Desktop/04_WORKSPACE/00-WORKSPACE/billnet_client/src/app/share/safe.pipe.ts[1, 1]: missing file header
ERROR: (completed-docs) C:/Users/WQ35311/Desktop/04_WORKSPACE/00-WORKSPACE/billnet_client/src/app/share/safe.pipe.ts[4, 1]: Documentation must exist for exported classes.
ERROR: (completed-docs) C:/Users/WQ35311/Desktop/04_WORKSPACE/00-WORKSPACE/billnet_client/src/app/share/safe.pipe.ts[8, 5]: Documentation must exist for methods.

**Comment by wKoza** [comment]
Hi @chengwanxin9825 ,
`pipe-naming` is now deprecated. You should drop this rule of your tslint file.

**Comment by chengwanxin9825** [comment]
@wKoza  
thank you very march.
