### ISSUE TITLE
TypeError: ts.isStringLiteralLike is not a function

### ISSUE THREAD

**Issue by 82antu** [mgechev/codelyzer#669]
Hi,

I just update right now from 4.3.0 to 4.4.0,...and:

```
TypeError: ts.isStringLiteralLike is not a function
    at SelectorValidatorWalker.validateProperty (/home/one/master/hfw-core/node_modules/codelyzer/selectorNameBase.js:136:19)
    at /home/one/master/hfw-core/node_modules/codelyzer/selectorNameBase.js:111:85
    at Array.filter (<anonymous>)
    at SelectorValidatorWalker.validateSelector (/home/one/master/hfw-core/node_modules/codelyzer/selectorNameBase.js:111:14)
    at SelectorValidatorWalker.validateDecorator (/home/one/master/hfw-core/node_modules/codelyzer/selectorNameBase.js:102:18)
    at Array.forEach (<anonymous>)
    at SelectorValidatorWalker.visitClassDeclaration (/home/one/master/hfw-core/node_modules/codelyzer/selectorNameBase.js:95:45)
    at SelectorValidatorWalker.SyntaxWalker.visitNode (/home/one/master/hfw-core/node_modules/tslint/lib/language/walker/syntaxWalker.js:314:22)
    at /home/one/master/hfw-core/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitEachNode (/home/one/master/hfw-core/node_modules/typescript/lib/typescript.js:15956:30)
TypeError: ts.isStringLiteralLike is not a function
    at Object.exports.isSimpleTemplateString (/home/one/master/hfw-core/node_modules/codelyzer/util/utils.js:5:15)
    at /home/one/master/hfw-core/node_modules/codelyzer/util/astQuery.js:33:57
    at /home/one/master/hfw-core/node_modules/codelyzer/util/function.js:20:59
    at Maybe.bind (/home/one/master/hfw-core/node_modules/codelyzer/util/function.js:17:54)
    at Maybe.fmap (/home/one/master/hfw-core/node_modules/codelyzer/util/function.js:20:21)
    at Object.getStringInitializerFromProperty (/home/one/master/hfw-core/node_modules/codelyzer/util/astQuery.js:33:10)
    at /home/one/master/hfw-core/node_modules/codelyzer/angular/metadataReader.js:42:55
    at Maybe.bind (/home/one/master/hfw-core/node_modules/codelyzer/util/function.js:17:54)
    at MetadataReader.readDirectiveMetadata (/home/one/master/hfw-core/node_modules/codelyzer/angular/metadataReader.js:42:14)
    at MetadataReader.readComponentMetadata (/home/one/master/hfw-core/node_modules/codelyzer/angular/metadataReader.js:49:38)
```

Any help is appreciate.

thank in advance

**Comment by LukasKlement** [comment]
I'm experiencing the same issue, downgrading to version 4.3.0 fixes it.
