### ISSUE TITLE
Cannot parse the styles

### ISSUE THREAD

**Issue by tahuba** [mgechev/codelyzer#680]
I'm running codelyzer, and it gives lot of these error message:
```
Cannot parse the styles of AlertComponent TypeError: Cannot read property 'visit' of null
    at BasicCssAstVisitor.visitCssDefinition (/home/tahuba/git/???/node_modules/codelyzer/angular/styles/basicCssAstVisitor.js:57:19)
    at CssDefinitionAst.visit (/home/tahuba/git/???/node_modules/codelyzer/angular/styles/cssAst.js:191:24)
    at /home/tahuba/git/???/node_modules/codelyzer/angular/styles/basicCssAstVisitor.js:68:27
    at Array.forEach (<anonymous>)
    at BasicCssAstVisitor.visitCssStylesBlock (/home/tahuba/git/???/node_modules/codelyzer/angular/styles/basicCssAstVisitor.js:67:25)
    at CssStylesBlockAst.visit (/home/tahuba/git/???/node_modules/codelyzer/angular/styles/cssAst.js:271:24)
    at BasicCssAstVisitor.visitCssSelectorRule (/home/tahuba/git/???/node_modules/codelyzer/angular/styles/basicCssAstVisitor.js:41:19)
    at CssSelectorRuleAst.visit (/home/tahuba/git/???/node_modules/codelyzer/angular/styles/cssAst.js:177:24)
    at /home/tahuba/git/???/node_modules/codelyzer/angular/styles/basicCssAstVisitor.js:74:21
    at Array.forEach (<anonymous>)
```

Node: v10.5.0
Angular: v6.0.6
Typescript: v2.7.2
Codelyzer: v4.3.0

**Comment by rafaelss95** [comment]
Can you show the code of the file which throws this error? Also, have you checked if it's still an issue with the latest version (4.4.2)?

**Comment by tahuba** [comment]
The error thrown on line `styleUrls: ['./login.style.scss'],` in the @Component decorator in all of my components. Previously I used the version 4.3.0 and there wasn't error. The error appeared after the upgrade to version 4.4.2.

**Comment by mgechev** [comment]
Closing it due to insufficient information.
