### ISSUE TITLE
Codelyzer fails because PropertyBindingType is not exported in Angular 6.1.0

### ISSUE THREAD

**Issue by tahuba** [mgechev/codelyzer#696]
I get this error to all of my Components:
```
TypeError: Cannot read property 'Animation' of undefined
    at getExpressionDisplacement (/home/myuser/git/my-project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:28:46)
    at BasicTemplateAstVisitor.visitElementProperty (/home/myuser/git/my-project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:126:68)
    at BoundElementPropertyAst.visit (/home/myuser/git/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:1273:28)
    at BasicTemplateAstVisitor.visit (/home/myuser/git/my-project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:83:12)
    at /home/myuser/git/my-project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:106:60
    at Array.forEach (<anonymous>)
    at BasicTemplateAstVisitor.visitElement (/home/myuser/git/my-project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:106:24)
    at ElementAst.visit (/home/myuser/git/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:1362:28)
    at BasicTemplateAstVisitor.visit (/home/myuser/git/my-project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:83:12)
    at /home/myuser/git/my-project/node_modules/codelyzer/angular/templates/basicTemplateAstVisitor.js:109:62
```

`PropertyBindingType` is not exported since v6.1.0 @angular/compiler.

**Comment by tahuba** [comment]
Details: https://github.com/angular/angular/issues/25241
