### ISSUE TITLE
Install Codelyzer globally

### ISSUE THREAD

**Issue by KevinFernandes** [mgechev/codelyzer#74]
Can Codelyzer be installed globally next to a globally installed tslint?
What path would I specify in my local tslint.json?

When I try to use locally installed Codelyzer with a globally installed tslint, it looks like Codelyzer expects to be installed side-by-side with tslint, I get the following error:

Error: Cannot find module 'tslint/lib/lint'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\SVN\CAzE-2.1.00\TestProjects\TypescriptApp\XXXXXXX\node_modules\codelyzer\selectorNameBase.js:8:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

I have lots of projects and would prefer not installing tslint in every one of them (it takes up space and would be a logistical nightmare to keep them all in sync).  Installing globally is the best option I have.

**Comment by mgechev** [comment]
Codelyzer is an addition to tslint (extra, Angular specific rules on top). When (if) we fork tslint we are going to export it as a global executable file.
