### ISSUE TITLE
TS parse Error

### ISSUE THREAD

**Issue by TheRealMrCrowley** [mgechev/codelyzer#78]
```
TypeError: Cannot read property 'text' of undefined
at LOCAL_PATH_TO_NODE_MODULES\Angular\node_modules\codelyzer\usePipeTransformInterfaceRule.js:31:85
at Array.map (native)
at ClassMetadataWalker.visitClassDeclaration (LOCAL_PATH_TO_NODE_MODULES\Angular\node_modules\codelyzer\usePipeTransformInterfaceRule.js:31:36)
at ClassMetadataWalker.SyntaxWalker.visitNode (LOCAL_PATH_TO_NODE_MODULES\Angular\node_modules\tslint\lib\language\walker\syntaxWalker.js:264:22)
at LOCAL_PATH_TO_NODE_MODULES\Angular\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
at visitEachNode (LOCAL_PATH_TO_NODE_MODULES\Angular\node_modules\typescript\lib\typescript.js:7255:30)
at Object.forEachChild (LOCAL_PATH_TO_NODE_MODULES\Angular\node_modules\typescript\lib\typescript.js:7412:24)
at ClassMetadataWalker.SyntaxWalker.walkChildren (LOCAL_PATH_TO_NODE_MODULES\Angular\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)
at ClassMetadataWalker.SyntaxWalker.visitSourceFile (LOCAL_PATH_TO_NODE_MODULES\Angular\node_modules\tslint\lib\language\walker\syntaxWalker.js:190:14)
at ClassMetadataWalker.SyntaxWalker.visitNode (LOCAL_PATH_TO_NODE_MODULES\Angular\node_modules\tslint\lib\language\walker\syntaxWalker.js:414:22)
```

The issue is caused when using `@Injectable()` without the parenthases

i fixed the real issue by sheer dumb luck, so if you could create an error that is readable for these mistakes that would be great

**Comment by mnn** [comment]
Oh my god, just spent half an hour figuring out what is causing build suddenly crashing and it turns out it's missing parentheses :(. What a useless crash message.

**Comment by mgechev** [comment]
@mnn you can try updating to the latest version of codelyzer, the issue should have been fixed.
