### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by rolandjitsu** [mgechev/codelyzer#83]
I get the following:
```bash
TypeError: Cannot read property 'kind' of undefined
    at /Users/rolandjitsu/Projects/infarm/dashboard/node_modules/codelyzer/selectorNameBase.js:79:50
    at Array.forEach (native)
    at SelectorNameValidatorWalker.validateSelector (/Users/rolandjitsu/Projects/infarm/dashboard/node_modules/codelyzer/selectorNameBase.js:77:18)
    at SelectorNameValidatorWalker.validateDecorator (/Users/rolandjitsu/Projects/infarm/dashboard/node_modules/codelyzer/selectorNameBase.js:70:18)
    at Array.forEach (native)
    at SelectorNameValidatorWalker.visitClassDeclaration (/Users/rolandjitsu/Projects/infarm/dashboard/node_modules/codelyzer/selectorNameBase.js:58:33)
    at SelectorNameValidatorWalker.SyntaxWalker.visitNode (/Users/rolandjitsu/Projects/infarm/dashboard/node_modules/tslint/lib/language/walker/syntaxWalker.js:264:22)
    at /Users/rolandjitsu/Projects/infarm/dashboard/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/Users/rolandjitsu/Projects/infarm/dashboard/node_modules/typescript/lib/typescript.js:8247:30)
    at Object.forEachChild (/Users/rolandjitsu/Projects/infarm/dashboard/node_modules/typescript/lib/typescript.js:8405:24)
    at SelectorNameValidatorWalker.SyntaxWalker.walkChildren (/Users/rolandjitsu/Projects/infarm/dashboard/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:12)
    at SelectorNameValidatorWalker.SyntaxWalker.visitBlock (/Users/rolandjitsu/Projects/infarm/dashboard/node_modules/tslint/lib/language/walker/syntaxWalker.js:28:14)
    at SelectorNameValidatorWalker.SyntaxWalker.visitNode (/Users/rolandjitsu/Projects/infarm/dashboard/node_modules/tslint/lib/language/walker/syntaxWalker.js:249:22)
    at /Users/rolandjitsu/Projects/infarm/dashboard/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitNode (/Users/rolandjitsu/Projects/infarm/dashboard/node_modules/typescript/lib/typescript.js:8235:20)
    at Object.forEachChild (/Users/rolandjitsu/Projects/infarm/dashboard/node_modules/typescript/lib/typescript.js:8323:21)
```

I'm using:
- *codelyzer*: `0.0.28`
- *tslint*: `3.15.1`
- *ts-node*: `1.3.0`
- *typescript*: `2.0.2`

**Comment by preslavsh** [comment]
Can I see a code snippet of the file you are running codelyzer on?

**Comment by rolandjitsu** [comment]
@preslavsh Unfortunately I run it on probably around 200+ TS files, so I am not sure where it fails. Also, due to an NDA, I am not allowed to disclose any code. And the error does not seem to provide any clue which file that may be.

**Comment by rolandjitsu** [comment]
At least I can tell you that the following rules cause that error:
```js
{
    "component-selector-name": [true, "kebab-case"],
    "directive-selector-type": [true, "attribute"],
    "component-selector-type": [true, "element"],
    "directive-selector-prefix": [true, "infarm"],
    "component-selector-prefix": [true, "infarm"]
}
```

**Comment by preslavsh** [comment]
I have created PR for that, but it's only a smart guess.

**Comment by rolandjitsu** [comment]
Ok, so it boils down to this:
```js
private static createComponent(selector: string, template: string): any {
	@Component({selector, template})
	class DynamicComponent {}
	return DynamicComponent;
}
```

I have a service that creates dynamic modules/components.

**Comment by rolandjitsu** [comment]
The following does not throw:
```js
@Component({selector: selector, template: template})
```

But then I get errors for the shorthand rule:
```bash
(object-literal-shorthand) app/shared/component-builder/type-builder.service.ts[15, 15]: Expected property shorthand in object literal.
(object-literal-shorthand) app/shared/component-builder/type-builder.service.ts[15, 35]: Expected property shorthand in object literal.
```

**Comment by mgechev** [comment]
@rolandjitsu thanks for digging into this! With the information you provided we should be able to fix it in by a day or two.

**Comment by rolandjitsu** [comment]
@mgechev no worries, @preslavsh pointed me in the right direction.

**Comment by mgechev** [comment]
@rolandjitsu I will not publish to npm in the next a couple of days. I'm planning a bigger release which includes template support.
