### ISSUE TITLE
directive-selector throws an error when it comes across an empty @Directive()

### ISSUE THREAD

**Issue by BramMeerten** [mgechev/codelyzer#965]
**Describe the bug**

When you have the following annotation:
```
@Directive()
export abstract class MyDirective {}
```

The `directive-selector` rule crashes with the following error:
```
The 'directive-selector' rule threw an error in '/Users/bram/jnj/src/ui/coreui/src/grid/filter/data-grid-filter/abstract-datagrid-filter.directive.ts':
TypeError: Cannot read property 'kind' of undefined
    at Object.isObjectLiteralExpression (/Users/[...]/node_modules/typescript/lib/typescript.js:15278:21)
    at SelectorValidatorWalker.validateSelector (/Users/[...]/node_modules/@com.jnj.gtsc/tslint-rules-angular/node_modules/codelyzer/selectorNameBase.js:107:17)
    at SelectorValidatorWalker.validateDecorator (/Users/[...]/node_modules/@com.jnj.gtsc/tslint-rules-angular/node_modules/codelyzer/selectorNameBase.js:102:18)
    at Array.forEach (<anonymous>)
    at SelectorValidatorWalker.visitClassDeclaration (/Users/[...]/node_modules/@com.jnj.gtsc/tslint-rules-angular/node_modules/codelyzer/selectorNameBase.js:95:45)
    at SelectorValidatorWalker.SyntaxWalker.visitNode (/Users/[...]/node_modules/tslint/lib/language/walker/syntaxWalker.js:314:22)
    at /Users/[...]/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/[...]/node_modules/typescript/lib/typescript.js:17774:30)
    at Object.forEachChild (/Users/[...]/node_modules/typescript/lib/typescript.js:18007:24)
    at SelectorValidatorWalker.SyntaxWalker.walkChildren (/Users/[...]/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)

```

**Context and configuration**
`tsconfig.json`:
```
{
    "rules": {
        "directive-selector": [
            true,
            "attribute",
            "demo",
            "camelCase"
        ]
    }
}
```

**Expected behavior**

Expected no error to be thrown.

**Environment**

 - Version 5.2.1
 - Node.js version 13.10.1
 - Package manager (yarn/npm) version 6.14.2
 - Angular version 9.1.7
 - tslint version 5.11.0

**Additional context**

Might seem weird to have an empty `@Directive()`, but when upgrading to angular 9,[ angular adds this automatically](https://angular.io/guide/migration-undecorated-classes).
For example `BaseClass` is expected to have an `@Directive()`:
```
@Directive()
export class BaseMenu {
  constructor(private vcr: ViewContainerRef) {}
}

@Directive({selector: '[settingsMenu]'})
export class SettingsMenu extends BaseMenu {}
```

**Comment by BramMeerten** [comment]
You can circumvent this bug by adding `{}`: `@Directive({})`

**Comment by BramMeerten** [comment]
Sorry, thought I was using version 5.2.1 but wasn't.
This is not an issue in the latest versions.
